"project_id": "756295"
"api_token": "8bb60d319d9de859e36ae0e7eb21f88edcefc3da0f7fa7bda559670491177d2d457bc6daafdf3dd7"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

"files": [
  {
    "source": "/app/src/main/res/values/strings.xml",
    "translation": "/app/src/main/res/values-%two_letters_code%/strings.xml"
  },
]