name: Build and Release APK

on:
  workflow_dispatch: # Trigger only when manually started

permissions:
  contents: write

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    env:
      # Set environment variables for signing at the job level
      RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
      RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
      RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Retrieve and decode keystore file
      - name: Prepare Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE_64 }}" | base64 -d > app/keystore.jks

      - name: Check Keystore File Location
        run: ls -l app/

      # Cache Gradle dependencies
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Extract version name from build.gradle.kts file
      - name: Extract Version Name
        id: extract_version
        run: |
          version_name=$(grep -oP 'versionName\s+"(.*?)"' app/build.gradle.kts | sed -E 's/versionName "(.*)"/\1/')
          echo "VERSION_NAME=$version_name" >> $GITHUB_ENV

      # Build APK without -P properties
      - name: Build APK
        run: ./gradlew assembleRelease

      # Upload APK artifacts (keep as output for next job)
      - name: Upload APK artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk

  release:
    name: Upload APK to GitHub Release
    runs-on: ubuntu-latest
    needs: build  # This job depends on the build job

    steps:
      # Checkout the code (to ensure access to the repository)
      - name: Checkout Code
        uses: actions/checkout@v3

      # Download the APK artifact from the previous job
      - name: Download APK artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-apk
          
      - name: Verify downloaded artifact contents
        run: ls -al

      # Upload release APK to GitHub
      - name: Upload APK to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./release-apk/*.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: "Release v${{ env.VERSION_NAME }}"
          draft: false
          prerelease: false
